### ISSUE TITLE
Attach Screenshot Tab doesnt work

### ISSUE THREAD

**Issue by roshanroche** [cconard96/glpi-screenshot-plugin#1]
Hi Conard,

The tab attach screenshot doesn't respond while clicking on it. 

Browser : Chrome Version 85.0.4183.121 (Official Build) (64-bit)

Same on Edge Version 85.0.564.63 (Official build) (64-bit)

Uncaught TypeError: Cannot read property 'getDisplayMedia' of undefined
    at captureScreenshot (screenshot.js?v=1.0.0:34)
    at HTMLLIElement.<anonymous> (screenshot.js?v=1.0.0:73)
    at HTMLDocument.dispatch (jquery.js:5429)
    at HTMLDocument.elemData.handle (jquery.js:5233)

**Comment by cconard96** [comment]
I'll have to check. I'm guessing this is a Windows client?

**Comment by roshanroche** [comment]
Hi Conard,

Yea I'm trying it on a windows client. Windows 10 64 bit. 

Glpi on centos 8

**Comment by cconard96** [comment]
Is your GLPI using HTTPs? It works for me when connecting to my GLPI using "localhost' (HTTP) and remotely using HTTPs. I found something that said this feature was only working over HTTPs as of Chrome 74. I think localhost is the only exclusion.

**Comment by roshanroche** [comment]
Hi Conard,
It's http and using a FQDN. The error is under Chrome developer tools. Every time I click on the tab it throws this error.

**Comment by cconard96** [comment]
The media API only works over HTTPS. That is a Chrome limitation (and part of the spec for that feature), and not something wrong with the plugin unfortunately.
