### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by Cr2zyy** [cconard96/glpi-screenshot-plugin#14]
Hi, im trying to install this plugin, but when i click in the install button, nothing happens, the loading icon appears than i go back to "install". Why is that? I'm using GLPI 9.5, lastet.

**Comment by cconard96** [comment]
Can you verify that your GLPI server is using HTTPS? Are there any entries in files/_logs/php-errors.log or the sql-errors.log file from around the time you tried installing.

**Comment by Cr2zyy** [comment]
Hello, 

Yes, i get an error:

[2021-01-10 14:48:47] glpiphplog.ERROR: Plugin::getInfo() in /var/www/html/site.com.br/web/inc/plugin.class.php line 1473
plugin_version_screenshot method must be defined!  {"user":"37@b:u:user:1"}

**Comment by cconard96** [comment]
Looks like GLPI cannot read the setup.php file in the plugin folder. Can you check it exists and verify the permissions on it (and the rest of the plugin folder).

**Comment by Cr2zyy** [comment]
This plugin is the only one im having trouble, the others installed just fine even with no setup.php file in the plugin folder.

**Comment by cconard96** [comment]
All plugins need a setup.php file in their folders (like screenshot/setup.php) or GLPI will complain with errors similar to what you saw.
When I was talking about checking permissions, I meant specifically on the "plugin/screenshot" or "marketplace/screenshot" folder and the files within it.

**Comment by Cr2zyy** [comment]
There is a setup.php file in folder, and permissions are the same than the others plugins. This is the only one i'm having trouble to install, don't know why.

**Comment by Cr2zyy** [comment]
I'm having this error now in sql error log, when i click to install

  *** MySQL query error:
  SQL: INSERT INTO `glpi_profilerights` (`id`, `profiles_id`, `name`, `rights`) VALUES (NULL, '1', 'plugin_screenshot_recording', '0')
  Error: Column 'id' cannot be null

**Comment by akhlaaqbadulla** [comment]
i am having the same trouble on glpi 9.5.2 it works fine but it wont install in 9.5.3. i am in http and having the same errors.
i tried even even tried to give it superuser right it still won't install.

**Comment by cconard96** [comment]
Using the MySQL command line or your preferred DB tool, please run `DESCRIBE glpi_profilerights` and verify it says `auto_increment` in the Extra column for the ID field.
This shouldn't have anything to do with the plugin, bit maybe something else broke the auto increment on the table.

If the auto increment is missing, please list the other plugins and versions used. If you know of any differences in plugin versions from the working instance to the broken one?

**Comment by akhlaaqbadulla** [comment]
Everything seem fine with the database and i even ran `php bin/console db:check` just to be sure and there is no issue. Also my instance is a clean install on a new virtual machine. As i mentioned earlier my production instance is version 9.5.2 and there is no issue with the screenshot plugins.On the 9.5.3 instance i have installed several plugins and only screenshot is not installing.

**Comment by akhlaaqbadulla** [comment]
Well it’s my lucky day.

i was able to install it with these commands.

```
./bin/console glpi:plugin:install Screenshot
./bin/console glpi:plugin:activate Screenshot
```

not what i expected but Atleast it’s installed not i need to find out why.

**Comment by paccojp** [comment]
Estava com problema na instalação utilizando o Mozila Firefox, mais se você utilizar o Chorme (adicionando o https:// antes, você consegue instalar e utilizar. Se você for para o Mozila ele vai aparecer como instalado, mas quando clicar em screenshort não vai funcionar, somente no chrome.

**Comment by DamBn** [comment]
Quel est le format d'enregistrement des captures vidéos ?

**Comment by cconard96** [comment]
> Quel est le format d'enregistrement des captures vidéos ? 
> 

Webm
