### ISSUE TITLE
Share Screenshot doesen't work

### ISSUE THREAD

**Issue by B3fa** [cconard96/glpi-screenshot-plugin#15]
Hello,

When I add a screenshot or other capture that displays it (new item), I click on download and the screenshot disappears.

latest version of GLPI on Windows 10 for testing, did I forget a parameter?

thank you

**Comment by cconard96** [comment]
Do you have an errors in files/_log/php-errors.log around the time you tried uploading the screenshot? Also, you I get the Screenshot plugin version?

**Comment by DavidFS93** [comment]
Hello,

I have the same problem. Last version of GLPI(9.5.4) and screenshot plugin (1.1.2). When I click on the screenshot Button i can see the screenshot but the Download button made it disappear.
I have check php_error but nothing in there. Only error i got is
"includeLocales(statusertask_report_title, reports) => not found" and does not seems to be related to this problem.

If you have any idea i will be glad to test :)

**Comment by cconard96** [comment]
Is the image filetype set to be allowed to upload? See my comment in #16. By default both screenshot formats should be allowed (jpg and png). I know the default recording format (webm) is not allowed by default and must be added.
Another thing to check is that manually adding a document of the same filetype works properly.

**Comment by DavidFS93** [comment]
I just tried, manually adding file is working fine.
I didn't change the webm authorization before but in this case it clearly show that the filetype isn't allowed. Regarding JPEG/PNG it just don't show any message

**Comment by cconard96** [comment]
Can you provide the web server (IIS, Apache, etc), server OS (Windows, Linux, etc) and a list of plugins (enabled or not) so I can try and recreate the issue locally?

**Comment by DavidFS93** [comment]
Here the information for my server : 
Operating system: Linux FS-XXXX 4.9.0-15-amd64 #1 SMP Debian 4.9.258-1 (2021-03-08) x86_64
PHP 8.0.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mailparse, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, yaml, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.25 (Debian) (Apache/2.4.25 (Debian) Server at glpi.XXXX.com Port 443)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0 Waterfox/78.8.0
Server Software: Debian 9.13
	Server Version: 10.1.48-MariaDB-0+deb9u1

Plugin list : Screenshot(V1.1.2), DataInjection (V2.9.0), FormCreator (V2.11.2), FusionInventory(V9.5+2.0), Order(V2.6.0), manufacturersimports(V2.3.1), mreporting(V1.7.1) and Reports (V1.14.0)

**Comment by cconard96** [comment]
Thank for that information. I'll try to test this and get back to you on this tonight (I'm at my other job right now).

**Comment by DavidFS93** [comment]
I'm not in a hurry it was more a matter of convenience. Take your time ;)

**Comment by cconard96** [comment]
I think I recreated the issue with a new install of the plugin. I forgot to add the default image format option to the DB during the install so it was failing because of that. Can you try going to Setup > General > Screenshot and just hitting save to force the default option to be saved to the database, then try uploading again?

**Comment by DavidFS93** [comment]
It's Working well once configuration forced 👍 
Thanks

**Comment by cconard96** [comment]
Fixed in 1.1.3 or with the mentioned solution of saving the config.
