### ISSUE TITLE
Screen recording issue

### ISSUE THREAD

**Issue by kfra71** [cconard96/glpi-screenshot-plugin#16]
it looks like screen recoding filetype is not authorised by default GLPI settings.

Can you kindly let me know which the right format to add?

**Comment by cconard96** [comment]
In Setup > Dropdowns > Document Types add the file extension the
screenshots are being saved with (jpg, jpeg, or png) if they don't already
exist. Then, make sure the option in them for allowing upload is set to
true.

**Comment by kfra71** [comment]
Thanks, now it works like a charm!
