### ISSUE TITLE
Localization, Russian language

### ISSUE THREAD

**Issue by BorisNovg** [cconard96/glpi-screenshot-plugin#19]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Messages and buttons in russian language

**Describe alternatives you've considered**
My own ru_RU.po and ru_RU.mo in /usr/share/glpi/plugins/screenshot/locales

**Additional context**
Files ru_RU.po and ru_RU.mo attached.
[ru_RU.mo.po.zip](https://github.com/cconard96/glpi-screenshot-plugin/files/7104373/ru_RU.mo.po.zip)

**Comment by cconard96** [comment]
Localization is done on the POEditor platform and then exported here before a release. I've added the Russian language and imported the translations from your PO file. If you want to contribute to future translations, you can request access and I'll grant it.
https://poeditor.com/join/project?hash=FBDufdxixj

Version 1.1.4 will be released soon with this new locale.
