### ISSUE TITLE
Cannot update to version 1.1.4 via marketplace

### ISSUE THREAD

**Issue by jackburton79** [cconard96/glpi-screenshot-plugin#20]
GLPI Version 9.5.5.
Screenshot plugin version 1.1.3 is installed through the marketplace.
When I tried to update it through marketplace nothing happens. 

In php_errors.log I get these errors:
[2021-09-10 09:36:47] glpiphplog.CRITICAL:   *** Uncaught Exception UnexpectedValueException: internal corruption of phar "/usr/local/share/glpi/files/_tmp/glpi-screenshot-v1.1.4.tar.bz2" (truncated entry) in /usr/local/share/glpi/vendor/wapmorgan/unified-archive/src/Formats/Tar.php at line 320
  Backtrace :
  ...pmorgan/unified-archive/src/Formats/Tar.php:320 PharData->__construct()
  ...pmorgan/unified-archive/src/Formats/Tar.php:292 wapmorgan\UnifiedArchive\Formats\Tar->open()
  ...rgan/unified-archive/src/UnifiedArchive.php:255 wapmorgan\UnifiedArchive\Formats\Tar->__construct()
  ...rgan/unified-archive/src/UnifiedArchive.php:105 wapmorgan\UnifiedArchive\UnifiedArchive->__construct()
  inc/marketplace/controller.class.php:117           wapmorgan\UnifiedArchive\UnifiedArchive::open()
  ajax/marketplace.php:69                            Glpi\Marketplace\Controller->downloadPlugin()

It seems it downloads a glpi-screenshot-v1.1.4.tar.bz2 file in glpi/files/_tmp which is 14 bytes only.

**Comment by cconard96** [comment]
It looks like the GitHub action that creates the releases failed silently (and reported success). I've manually fixed the release archive. Please try updating from the marketplace again.

**Comment by jackburton79** [comment]
I tried again:
now it goes a bit forward and I got this:
[2021-09-10 11:42:24] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined offset: 1 in /usr/local/share/glpi/vendor/laminas/laminas-i18n/src/Translator/Loader/Gettext.php at line 145
  Backtrace :
  .../laminas-i18n/src/Translator/Translator.php:745 Laminas\I18n\Translator\Loader\Gettext->load()
  .../laminas-i18n/src/Translator/Translator.php:617 Laminas\I18n\Translator\Translator->loadMessagesFromFiles()
  .../laminas-i18n/src/Translator/Translator.php:440 Laminas\I18n\Translator\Translator->loadMessages()
  .../laminas-i18n/src/Translator/Translator.php:389 Laminas\I18n\Translator\Translator->getTranslatedMessage()
  inc/autoload.function.php:187                      Laminas\I18n\Translator\Translator->translatePlural()
  plugins/room/setup.php:46                          _n()
  inc/plugin.class.php:1471                          plugin_version_room()
  inc/plugin.class.php:1511                          Plugin::getInfo()
  inc/plugin.class.php:438                           Plugin->getInformationsFromDirectory()
  inc/plugin.class.php:421                           Plugin->checkPluginState()
  inc/plugin.class.php:208                           Plugin->checkStates()
  inc/includes.php:106                               Plugin->init()
  ajax/displayMessageAfterRedirect.php:34            include()

**Comment by cconard96** [comment]
It looks like that error is from the room plugin's code. I don't see the
translation function being used at all in the setup file as indicated in
the latest code. However I do see it in an unmerged pull request for 9.5
compatibility.
It looks like where the bad code is, it will continue throwing these errors
even of the plugin is disabled.

**Comment by jackburton79** [comment]
Right, sorry.
In the GUI, though I get this when I try to update the screenshot plugin:
![image](https://user-images.githubusercontent.com/3501519/132836104-f08ab7d9-cca7-4f1a-9d70-c1b7b0392aa1.png)
but the plugin is not updated. Moreover, with debug enabled:
/usr/local/share/glpi/vendor/laminas/laminas-i18n/src/Translator/Loader/Gettext.php at line 145

**Comment by cconard96** [comment]
No, I'm just dumb and didn't update the displayed version number. I just realized it is still 1.1.3.
As long as the new locale files are there (Portuguese (BR) and Russian), it is updated. There were no actual code changes between 1.1.3 and 1.1.4.
I fixed the version in the release archive so others don't get confused.

**Comment by jackburton79** [comment]
ok, thanks

**Comment by jackburton79** [comment]
Great! Now it worked just fine.
Thank you very much
![image](https://user-images.githubusercontent.com/3501519/132838501-1e58a8ff-ef84-4423-bb61-9b4530502589.png)
