### ISSUE TITLE
[GLPI 10] Icons to modify & delete sreeenshot on simplified interface

### ISSUE THREAD

**Issue by tsmr** [cconard96/glpi-screenshot-plugin#30]
![image](https://user-images.githubusercontent.com/13178158/152693973-061fc143-b0ea-418e-9fea-ca4f5d5bbe41.png)

On simplified interface, thu user have icons to modify & delete sreeenshot - but he haven't any right to do it. Hide these icons on simplified interface ?

**Comment by cconard96** [comment]
This plugin doesn't do anything unique with the display in the timeline (at least not yet). It just takes the screenshot and uploads it as a document to GLPI and associate it with the Ticket. This is a bug in the core.

Fixed by https://github.com/glpi-project/glpi/pull/10557
