### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by jackburton79** [cconard96/glpi-screenshot-plugin#35]
I noticed there is no italian translation.
I could help with one.
How do I start a new translation ?

**Comment by cconard96** [comment]
Hello,
I added the new language. You should be able to request access to it now.

https://poeditor.com/join/project/FBDufdxixj

**Comment by cconard96** [comment]
Access was granted.
After the translations are ready, I'll add them to this project and make a new bug-fix release for all supported versions (see Readme on main page of this repository).
