### ISSUE TITLE
Unauthorized file type

### ISSUE THREAD

**Issue by NazarovRoman** [cconard96/glpi-screenshot-plugin#37]
Hello!
I have a problem when recording screen using a plugin.
At the stage of uploading a file to the application, the system informs about "Unauthorized file type"

 
- GLPI 10.0.1
 - GLPI Server OS: centos7
 - Browser chrome 104.0.5112.102
 - Plugin version 2.0.1

![image](https://user-images.githubusercontent.com/40058572/186622206-a755a5e6-0ab6-4cb2-809c-78f4c2eeebc1.png)

**Comment by cconard96** [comment]
Hello, please make sure there is a Document Type added in GLPI (under Setup > Dropdowns) for the "video/webm" MIME and that the option in its for to allow upload is enabled.

You may also need to change the max upload size in the PHP config and in Setup > General > Management as these videos can get relatively large.

**Comment by NazarovRoman** [comment]
> 

Hello! Thank you very much for your quick response, it helped!
