### ISSUE TITLE
Erro Gravação de Tela - Formato inválido

### ISSUE THREAD

**Issue by belbatera** [cconard96/glpi-screenshot-plugin#38]
**Describe the bug**
A captura de tela ocorre normalmente, assim como a gravação de tela.
Entretanto, ao enviar a gravação, é exibida mensagem de erro.

**To Reproduce**
1. Go to 'Ticket'
2. Click on 'Gravação de Tela' 
3. Finalize a  gravação de tela
4. Envie a gravação
5. Veja a mensagem de erro

**Expected behavior**
Que a gravação fosse enviada assim como a captura de tela.

**Screenshots**
![Screenshot_1480](https://user-images.githubusercontent.com/29507543/191105104-385aaadc-dc2f-4a27-8fed-f343faf342f3.png)
![Screenshot_1479](https://user-images.githubusercontent.com/29507543/191105107-9af0f6fb-89d0-4a59-a335-746f786e5ad8.png)
![Screenshot_1478](https://user-images.githubusercontent.com/29507543/191105109-793ca9d6-c3c1-49e7-a9f4-b8a6c3bd7b23.png)
![Screenshot_1477](https://user-images.githubusercontent.com/29507543/191105110-591b0969-306c-4288-9938-a0fc2156dc55.png)

**System Specifications (please complete the following information):**
 GLPI 10.0.2 ( => /home2/villap89/atendimento.villapescados.com.br)
Installation mode: TARBALL
Current language:pt_BR

Operating system: Linux sh-pro32.hostgator.com.br 4.19.150-76.ELK.el7.x86_64 #1 SMP Wed Oct 7 01:33:43 CDT 2020 x86_64
PHP 8.0.16 litespeed (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, SourceGuardian, Zend OPcache, bcmath, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, json, libxml,
	litespeed, mbstring, mysqli, mysqlnd, odbc, openssl, pcntl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, pspell,
	readline, session, soap, sockets, sqlite3, standard, tidy, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="45" memory_limit="256M" post_max_size="32M" safe_mode="" session.save_handler="files"
	upload_max_filesize="32M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

**Additional context**

**Comment by lupin3rd** [comment]
https://github.com/cconard96/glpi-screenshot-plugin/issues/37

**Comment by cconard96** [comment]
The issue @lupin3rd linked should have the correct solution for this issue. For convience, here is my response from the linked issue (automatically translated):
O problema @lupin3rd vinculado deve ter a solução correta para esse problema. Por conveniência, aqui está minha resposta do problema vinculado (traduzido automaticamente):

Olá, certifique-se de que há um Tipo de Documento adicionado no GLPI (em Configuração > Listas suspensas) para o MIME "vídeo/webm" e que a opção em seu para permitir upload está ativada.

Você também pode precisar alterar o tamanho máximo de upload na configuração do PHP e em Configuração > Geral > Gerenciamento, pois esses vídeos podem ficar relativamente grandes.
