### ISSUE TITLE
Problem installing on GLPI 10.0.0.3

### ISSUE THREAD

**Issue by GGodoy21** [cconard96/glpi-screenshot-plugin#39]
Hello, I'm having trouble installing the Plugin in GLPI version 10.0.0.3 both through the marketplace and directly through the plugins folder.

Through the Marketplace I can download the plugin but I can't install it. The same occurs directly through the folder

I click install but nothing happens. I'm having this problem only with this plugin. I also tried to download a previous version of the plugin but it does not appear within the GLPI.
![image](https://user-images.githubusercontent.com/114604232/192834353-e46319db-6375-44fc-91ef-6a1dd2ce805e.png)

**Comment by cconard96** [comment]
Are you connecting to GLPI over HTTPS?

If not, the functionality of the plugin wouldn't be allowed by the browser.
There is a HTTPS check made when you try to install the plugin but the message "This plugin requires GLPI be served over HTTPS" isn't ever shown. I am aware of that issue.

**Comment by lexcorp** [comment]
Same here...

**Comment by cconard96** [comment]
In the `hook.php` file, can you try making the following change?

```diff
diff --git a/hook.php b/hook.php
index 92d9649..e1a0e33 100644
--- a/hook.php
+++ b/hook.php
@@ -22,7 +22,8 @@
 
 function plugin_screenshot_install()
 {
-   if (empty($_SERVER['HTTPS']) && !in_array($_SERVER['REMOTE_ADDR'], ['127.0.0.1', '::1'])) {
+   $is_https = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on') || $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https';
+   if (!$is_https && !in_array($_SERVER['REMOTE_ADDR'], ['127.0.0.1', '::1'])) {
       echo 'This plugin requires GLPI be served over HTTPS';
       return false;
    }
```

**Comment by lexcorp** [comment]
I get this:

[2022-10-11 15:28:29] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "HTTP_X_FORWARDED_PROTO" in /var/www/html/glpi/plugins/screenshot/hook.php at line 30
  Backtrace :
  src/Plugin.php:787                                 plugin_screenshot_install()
  front/plugin.form.php:51                           Plugin->install()

**Comment by lexcorp** [comment]
> I get this:
> 
> [2022-10-11 15:28:29] glpiphplog.WARNING: *** PHP Warning (2): Undefined array key "HTTP_X_FORWARDED_PROTO" in /var/www/html/glpi/plugins/screenshot/hook.php at line 30 Backtrace : src/Plugin.php:787 plugin_screenshot_install() front/plugin.form.php:51 Plugin->install()

FE DE ERRATAS...

Confirmo que se instala el plugin sin problemas, cuando se usa una conexión segura "https" y el certificado es valido.

**Comment by myrandor** [comment]
The fix from @cconard96 worked for me. I'm using a web proxy on port 80 to my docker, but my proxy is SSL.

**Comment by borkie** [comment]
The fix from @cconard96 worked
