### ISSUE TITLE
It is not displayed in the android application

### ISSUE THREAD

**Issue by aleadco** [cconard96/glpi-screenshot-plugin#4]
Apparently the screenshot is sent correctly but it is only seen in the web interface, in the android client application it is not displayed. I tried uploading an image and if it is displayed in the application.

**Comment by cconard96** [comment]
Which Android application are you using?

**Comment by aleadco** [comment]
https://play.google.com/store/apps/details?id=gal.tic.gapp.selfservice

**Comment by cconard96** [comment]
I'll try downloading that app later and running a few tests. To clarify, the "Attach Screenshot" button appears on Android and the image is uploaded and is visible from the web but not the app?

**Comment by aleadco** [comment]
> I'll try downloading that app later and running a few tests. To clarify, the "Attach Screenshot" button appears on Android and the image is uploaded and is visible from the web but not the app?

Yes, exactly

**Comment by aleadco** [comment]
> I'll try downloading that app later and running a few tests. To clarify, the "Attach Screenshot" button appears on Android and the image is uploaded and is visible from the web but not the app?

The button appears correctly in the browser and the capture is done correctly, but in the android application that screenshot is not displayed.

**Comment by cconard96** [comment]
I won't be able to debug this issue. The Gapp app doesn't work with self-signed certificates and I'm not exposing my development instance to the Internet to get a publicly issued certificate.
The Gapp app is a second-party app, and not my focus at the moment.
However, I can confirm that the mobile browsers for Android and iOS haven't implemented the API this plugin uses yet so I don't know how it works at all in that app.

See the following for tables of browsers supporting the APIs used:
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia#Browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/API/ImageCapture#Browser_compatibility

I may look into polyfills which would add this functionality to other browsers in the future.

**Comment by cconard96** [comment]
The features provided by this plugin are going to be integrated within GLPI itself starting in version 10.1. It doesn't make sense to evolve this plugin anymore. It will remain supported for GLPI 10.0.X and get bug fixes if needed, but I'm not focusing on new features.
At this point, mobile browsers still haven't completely implemented support for the required web APIs. If there is enough community interest for mobile support with the feature within GLPI itself during the GLPI 10.1 beta or after release, we may revisit this topic.
