### ISSUE TITLE
Add the screenshot button on the ticket creation form

### ISSUE THREAD

**Issue by monkkx** [cconard96/glpi-screenshot-plugin#45]
The screenhot could be added to the ticket at the time of the ticket creation, to save some time and make the ticket creation process smoother. However the Screenshot button is only visible on the ticket follow up update form, not on the creation form.

Please add a feature to add a screenshot in the ticket creation form.

**Comment by cconard96** [comment]
The screenshot/capture features provided by this plugin will be added to GLPI itself starting with GLPI 10.1. So, I'm only going to focus on bug fixes and maintaining support of this plugin with GLPI 10.
Feel free to test GLPI 10.1 once the beta is released (no ETA yet) and provide feedback regarding this feature at that time.
