### ISSUE TITLE
Update 1.1.0 failed

### ISSUE THREAD

**Issue by aleadco** [cconard96/glpi-screenshot-plugin#5]
When i try to update i get an error. This does not happen with the other applications. I tried disabling and and updating and nothing. Finally I tried uninstalling the application to install the new one and I get the same error.

![image](https://user-images.githubusercontent.com/35962168/96501632-9dc22f80-121e-11eb-9fe0-896e24ddd026.png)

**Comment by aleadco** [comment]
That's the only thing i get in the logs

` PHP Warning:  Unable to load plugin "screenshot" informations. in /var/www/html/inc/plugin.class.php on line 460`

**Comment by cconard96** [comment]
This is because 1.1 is not quite ready yet. I had begun to release it but held off because the new screen recording feature needs a bit more polish. I've fixed the plugin information so that it doesn't mess up the Marketplace listing anymore.
