### ISSUE TITLE
Error: Unauthorized file type

### ISSUE THREAD

**Issue by GuilhermeSt12** [cconard96/glpi-screenshot-plugin#50]
**Describe the bug**
When click to send video, return the error:
**Unauthorized file type**
Whats to do?

**To Reproduce**
1. Go to 'Respond' in the ticket
2. Click on 'Rec to screen'
3. See error

**Expected behavior**
The video send succesfull.

**Screenshots**
![image](https://github.com/user-attachments/assets/89867bda-c2d9-4162-a67f-4062ce11da80)

**System Specifications (please complete the following information):**
GLPI 10.0.7 ( => /usr/share/glpi)
Installation mode: TARBALL
Current language:pt_BR

**Comment by cconard96** [comment]
Is webm added as a known document type and authorized for upload in GLPI? Setup > Dropdowns > Document types.

**Comment by GuilhermeSt12** [comment]
![image](https://github.com/user-attachments/assets/17d8ea6b-84fa-4574-9292-fa70cc1be536)

Perfect! The configuration has been created is the problem solved! Thank you!
