### ISSUE TITLE
Add Wiki

### ISSUE THREAD

**Issue by cconard96** [cconard96/glpi-screenshot-plugin#8]
Improve new user experience by adding Wiki pages to this repository.

**Comment by danielloiola** [comment]
I want to help on localization to Portuguese Brazil...

**Comment by cconard96** [comment]
I've added to language to POEditor and added you as a contributor for it.

**Comment by cconard96** [comment]
The videos are ".webm" right now since that seems to be the only video type Firefox and Chrome both support.

**Comment by danielloiola** [comment]
Worked!! About to play the video, it's possible to play inside the ticket?

**Comment by cconard96** [comment]
Sorry for the late reply. This plugin does not add the ability to view the videos embedded in the ticket timeline. That is a bit out of scope of the goal of this plugin.
That would be better added into the core of GLPI or added by a different plugin.

**Comment by cconard96** [comment]
A basic Wiki is now available in this repository under the Wiki tab.
For the feedback about playing screen recordings directly within the timeline, see the open PR on the GLPI repository for adding support for this for the next version of GLPI.
https://github.com/glpi-project/glpi/pull/9296
