### ISSUE TITLE
Cannot install on GLPI 9.5.2

### ISSUE THREAD

**Issue by kofe88** [cconard96/glpi-screenshot-plugin#9]
Cannot install on GLPI 9.5.2 from folder plugins or from Marketplace.
The plugin is displayed in the list of available ones, but nothing happens when you click the install button.
![image](https://user-images.githubusercontent.com/16879167/99636468-82805500-2a54-11eb-8fb9-36f1a32b0d9d.png)
![image](https://user-images.githubusercontent.com/16879167/99636530-9af06f80-2a54-11eb-8ccc-a547f93d1c22.png)

**Comment by cconard96** [comment]
Are you connected to your GLPI over HTTPS or just HTTP? Since the features used in the plugin over work over HTTPS, it is meant not to install over HTTP.

**Comment by JavierKiconex** [comment]
thanks, it works perfectly on Firefoz Browser version 83 (64bit) windows 10

**Comment by cconard96** [comment]
Closing stale issue. If this continues to be an issue, feel free to re-open with the requested information.
Also, checking the GLPI log files for related errors may help me troubleshoot installation issues.
